/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import javax.swing.JOptionPane;

/**
 *
 * @author jez_3
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
       
        initComponents();
        setTitle("Conversor de Temperatura");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagen = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jTcelsius = new javax.swing.JTextField();
        jTfaraday1 = new javax.swing.JTextField();
        jBConvertir = new javax.swing.JButton();
        jLimagefondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setBackground(new java.awt.Color(0, 0, 255));
        jBSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBSalir.setText("Salir");
        jBSalir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanelImagen.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 80, 40));
        jPanelImagen.add(jTcelsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 40));
        jPanelImagen.add(jTfaraday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 40));

        jBConvertir.setBackground(new java.awt.Color(51, 51, 255));
        jBConvertir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBConvertir.setForeground(new java.awt.Color(255, 255, 255));
        jBConvertir.setText("Convertir");
        jBConvertir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jBConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConvertirActionPerformed(evt);
            }
        });
        jPanelImagen.add(jBConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 80, 40));

        jLimagefondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/conversordetemp.JPG"))); // NOI18N
        jPanelImagen.add(jLimagefondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConvertirActionPerformed
        // TODO add your handling code here:
        if (!jTfaraday1.getText().isEmpty()){
            
            
        float fara=Float.parseFloat(jTfaraday1.getText());
        float grado=((fara-32)*5)/9;
        
        JOptionPane.showMessageDialog(this, "Grados Celsius "+grado+" ºC");
        }
        
        if (!jTcelsius.getText().isEmpty()){
            
            
        float grado=Float.parseFloat(jTcelsius.getText());
        float Fara = 32 + (9 * grado / 5);
        JOptionPane.showMessageDialog(this, "Grados Fahrenheit "+Fara+" ºF");
        }
        
        limpiarCampos();
         
    }//GEN-LAST:event_jBConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void limpiarCampos(){
    jTfaraday1.setText("");
    jTcelsius.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConvertir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLimagefondo;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JTextField jTcelsius;
    private javax.swing.JTextField jTfaraday1;
    // End of variables declaration//GEN-END:variables
}
